apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-private-location-01
  labels:
    app: uptime-private-location-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-private-location-01
  template:
    metadata:
      labels:
        app: uptime-private-location-01
    spec:
      # 2GB ramdisk for shared memory is needed for fast Chrome user storage,
      # as well as a tmpfs for /home/uptime/run
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 2Gi
          name: ramdisk
        - emptyDir:
            medium: Memory
            sizeLimit: 128Mi
          name: tmpfs

      # !!TODO!! This may be required for Azure AKS or older container runtimes
      # to bind internally to ports 80 and 443
      # securityContext:
      #   sysctls:
      #     - name: "net.ipv4.ip_unprivileged_port_start"
      #       value: "0"

      containers:
        - name: uptime-private-location-01

          # !!TODO!! Set desired image version
          image: uptimecom/uptime-private-location:latest

          # CAP_NET_BIND_SERVICE is required to bind internally to ports 80 and 443
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE

          # 2 CPU cores/4GB RAM are the minimum recommended settings for running Chromium
          resources:
            requests:
              memory: "2Gi"
              cpu: "1.0"
            limits:
              memory: "4Gi"
              cpu: "2.0"

          # Make the 2GB shared memory ramdisk available to the container at /dev/shm,
          # and the tmpfs available at /home/uptime/run
          volumeMounts:
            - mountPath: /dev/shm
              name: ramdisk
            - mountPath: /home/uptime/run
              name: tmpfs

          ports:
            - containerPort: 443

          # !!TODO!! Set your Uptime.com Private Location API token here,
          # and set the available CPU cores per the `resources.limits.cpu` setting.
          env:
            - name: UPTIME_API_TOKEN
              value: "your-api-token"
            - name: UPTIME_AVAILABLE_CPU_CORES
              value: "2"
